apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: rideshare
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
