// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: location.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActiveDriverCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Long          float64                `protobuf:"fixed64,2,opt,name=long,proto3" json:"long,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,3,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveDriverCountRequest) Reset() {
	*x = ActiveDriverCountRequest{}
	mi := &file_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveDriverCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveDriverCountRequest) ProtoMessage() {}

func (x *ActiveDriverCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveDriverCountRequest.ProtoReflect.Descriptor instead.
func (*ActiveDriverCountRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{0}
}

func (x *ActiveDriverCountRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *ActiveDriverCountRequest) GetLong() float64 {
	if x != nil {
		return x.Long
	}
	return 0
}

func (x *ActiveDriverCountRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

type ActiveDriverCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveDriverCountResponse) Reset() {
	*x = ActiveDriverCountResponse{}
	mi := &file_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveDriverCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveDriverCountResponse) ProtoMessage() {}

func (x *ActiveDriverCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveDriverCountResponse.ProtoReflect.Descriptor instead.
func (*ActiveDriverCountResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{1}
}

func (x *ActiveDriverCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Long          float64                `protobuf:"fixed64,3,opt,name=long,proto3" json:"long,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateLocationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateLocationRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *UpdateLocationRequest) GetLong() float64 {
	if x != nil {
		return x.Long
	}
	return 0
}

type UpdateLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationResponse) Reset() {
	*x = UpdateLocationResponse{}
	mi := &file_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationResponse) ProtoMessage() {}

func (x *UpdateLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetNearbyDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Long          float64                `protobuf:"fixed64,2,opt,name=long,proto3" json:"long,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,3,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNearbyDriversRequest) Reset() {
	*x = GetNearbyDriversRequest{}
	mi := &file_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNearbyDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyDriversRequest) ProtoMessage() {}

func (x *GetNearbyDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyDriversRequest.ProtoReflect.Descriptor instead.
func (*GetNearbyDriversRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{4}
}

func (x *GetNearbyDriversRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GetNearbyDriversRequest) GetLong() float64 {
	if x != nil {
		return x.Long
	}
	return 0
}

func (x *GetNearbyDriversRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

type NearbyDriver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Long          float64                `protobuf:"fixed64,3,opt,name=long,proto3" json:"long,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,4,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	EstimatedEta  int32                  `protobuf:"varint,5,opt,name=estimated_eta,json=estimatedEta,proto3" json:"estimated_eta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyDriver) Reset() {
	*x = NearbyDriver{}
	mi := &file_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyDriver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyDriver) ProtoMessage() {}

func (x *NearbyDriver) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyDriver.ProtoReflect.Descriptor instead.
func (*NearbyDriver) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{5}
}

func (x *NearbyDriver) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *NearbyDriver) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *NearbyDriver) GetLong() float64 {
	if x != nil {
		return x.Long
	}
	return 0
}

func (x *NearbyDriver) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *NearbyDriver) GetEstimatedEta() int32 {
	if x != nil {
		return x.EstimatedEta
	}
	return 0
}

type GetNearbyDriversResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drivers       []*NearbyDriver        `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNearbyDriversResponse) Reset() {
	*x = GetNearbyDriversResponse{}
	mi := &file_location_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNearbyDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyDriversResponse) ProtoMessage() {}

func (x *GetNearbyDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyDriversResponse.ProtoReflect.Descriptor instead.
func (*GetNearbyDriversResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{6}
}

func (x *GetNearbyDriversResponse) GetDrivers() []*NearbyDriver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

var File_location_proto protoreflect.FileDescriptor

const file_location_proto_rawDesc = "" +
	"\n" +
	"\x0elocation.proto\x12\blocation\x1a\x1fgoogle/protobuf/timestamp.proto\"]\n" +
	"\x18ActiveDriverCountRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x12\n" +
	"\x04long\x18\x02 \x01(\x01R\x04long\x12\x1b\n" +
	"\tradius_km\x18\x03 \x01(\x01R\bradiusKm\"1\n" +
	"\x19ActiveDriverCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"V\n" +
	"\x15UpdateLocationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x12\n" +
	"\x04long\x18\x03 \x01(\x01R\x04long\"2\n" +
	"\x16UpdateLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\\\n" +
	"\x17GetNearbyDriversRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x12\n" +
	"\x04long\x18\x02 \x01(\x01R\x04long\x12\x1b\n" +
	"\tradius_km\x18\x03 \x01(\x01R\bradiusKm\"\x97\x01\n" +
	"\fNearbyDriver\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x12\n" +
	"\x04long\x18\x03 \x01(\x01R\x04long\x12\x1f\n" +
	"\vdistance_km\x18\x04 \x01(\x01R\n" +
	"distanceKm\x12#\n" +
	"\restimated_eta\x18\x05 \x01(\x05R\festimatedEta\"L\n" +
	"\x18GetNearbyDriversResponse\x120\n" +
	"\adrivers\x18\x01 \x03(\v2\x16.location.NearbyDriverR\adrivers2\xa5\x02\n" +
	"\x0fLocationService\x12U\n" +
	"\x0eUpdateLocation\x12\x1f.location.UpdateLocationRequest\x1a .location.UpdateLocationResponse\"\x00\x12[\n" +
	"\x10GetNearbyDrivers\x12!.location.GetNearbyDriversRequest\x1a\".location.GetNearbyDriversResponse\"\x00\x12^\n" +
	"\x11ActiveDriverCount\x12\".location.ActiveDriverCountRequest\x1a#.location.ActiveDriverCountResponse\"\x00B1Z/github.com/hugovillarreal/ridesharing/pkg/pb;pbb\x06proto3"

var (
	file_location_proto_rawDescOnce sync.Once
	file_location_proto_rawDescData []byte
)

func file_location_proto_rawDescGZIP() []byte {
	file_location_proto_rawDescOnce.Do(func() {
		file_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_proto_rawDesc), len(file_location_proto_rawDesc)))
	})
	return file_location_proto_rawDescData
}

var file_location_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_location_proto_goTypes = []any{
	(*ActiveDriverCountRequest)(nil),  // 0: location.ActiveDriverCountRequest
	(*ActiveDriverCountResponse)(nil), // 1: location.ActiveDriverCountResponse
	(*UpdateLocationRequest)(nil),     // 2: location.UpdateLocationRequest
	(*UpdateLocationResponse)(nil),    // 3: location.UpdateLocationResponse
	(*GetNearbyDriversRequest)(nil),   // 4: location.GetNearbyDriversRequest
	(*NearbyDriver)(nil),              // 5: location.NearbyDriver
	(*GetNearbyDriversResponse)(nil),  // 6: location.GetNearbyDriversResponse
}
var file_location_proto_depIdxs = []int32{
	5, // 0: location.GetNearbyDriversResponse.drivers:type_name -> location.NearbyDriver
	2, // 1: location.LocationService.UpdateLocation:input_type -> location.UpdateLocationRequest
	4, // 2: location.LocationService.GetNearbyDrivers:input_type -> location.GetNearbyDriversRequest
	0, // 3: location.LocationService.ActiveDriverCount:input_type -> location.ActiveDriverCountRequest
	3, // 4: location.LocationService.UpdateLocation:output_type -> location.UpdateLocationResponse
	6, // 5: location.LocationService.GetNearbyDrivers:output_type -> location.GetNearbyDriversResponse
	1, // 6: location.LocationService.ActiveDriverCount:output_type -> location.ActiveDriverCountResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_location_proto_init() }
func file_location_proto_init() {
	if File_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_proto_rawDesc), len(file_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_location_proto_goTypes,
		DependencyIndexes: file_location_proto_depIdxs,
		MessageInfos:      file_location_proto_msgTypes,
	}.Build()
	File_location_proto = out.File
	file_location_proto_goTypes = nil
	file_location_proto_depIdxs = nil
}
