// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ride.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	PickupLat     float64                `protobuf:"fixed64,2,opt,name=pickup_lat,json=pickupLat,proto3" json:"pickup_lat,omitempty"`
	PickupLong    float64                `protobuf:"fixed64,3,opt,name=pickup_long,json=pickupLong,proto3" json:"pickup_long,omitempty"`
	DropoffLat    float64                `protobuf:"fixed64,4,opt,name=dropoff_lat,json=dropoffLat,proto3" json:"dropoff_lat,omitempty"`
	DropoffLong   float64                `protobuf:"fixed64,5,opt,name=dropoff_long,json=dropoffLong,proto3" json:"dropoff_long,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RideRequest) Reset() {
	*x = RideRequest{}
	mi := &file_ride_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideRequest) ProtoMessage() {}

func (x *RideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ride_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideRequest.ProtoReflect.Descriptor instead.
func (*RideRequest) Descriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{0}
}

func (x *RideRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *RideRequest) GetPickupLat() float64 {
	if x != nil {
		return x.PickupLat
	}
	return 0
}

func (x *RideRequest) GetPickupLong() float64 {
	if x != nil {
		return x.PickupLong
	}
	return 0
}

func (x *RideRequest) GetDropoffLat() float64 {
	if x != nil {
		return x.DropoffLat
	}
	return 0
}

func (x *RideRequest) GetDropoffLong() float64 {
	if x != nil {
		return x.DropoffLong
	}
	return 0
}

type AcceptRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRideRequest) Reset() {
	*x = AcceptRideRequest{}
	mi := &file_ride_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRideRequest) ProtoMessage() {}

func (x *AcceptRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ride_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRideRequest.ProtoReflect.Descriptor instead.
func (*AcceptRideRequest) Descriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{1}
}

func (x *AcceptRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *AcceptRideRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type CompleteRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRideRequest) Reset() {
	*x = CompleteRideRequest{}
	mi := &file_ride_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRideRequest) ProtoMessage() {}

func (x *CompleteRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ride_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRideRequest.ProtoReflect.Descriptor instead.
func (*CompleteRideRequest) Descriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *CompleteRideRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type CancelRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRideRequest) Reset() {
	*x = CancelRideRequest{}
	mi := &file_ride_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRideRequest) ProtoMessage() {}

func (x *CancelRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ride_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRideRequest.ProtoReflect.Descriptor instead.
func (*CancelRideRequest) Descriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{3}
}

func (x *CancelRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *CancelRideRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRideRequest) Reset() {
	*x = GetRideRequest{}
	mi := &file_ride_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRideRequest) ProtoMessage() {}

func (x *GetRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ride_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRideRequest.ProtoReflect.Descriptor instead.
func (*GetRideRequest) Descriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{4}
}

func (x *GetRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

type RideHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // "rider" or "driver"
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RideHistoryRequest) Reset() {
	*x = RideHistoryRequest{}
	mi := &file_ride_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideHistoryRequest) ProtoMessage() {}

func (x *RideHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ride_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideHistoryRequest.ProtoReflect.Descriptor instead.
func (*RideHistoryRequest) Descriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{5}
}

func (x *RideHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RideHistoryRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RideHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RideHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Ride struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RiderId         string                 `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DriverId        *string                `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3,oneof" json:"driver_id,omitempty"`
	PickupLat       float64                `protobuf:"fixed64,4,opt,name=pickup_lat,json=pickupLat,proto3" json:"pickup_lat,omitempty"`
	PickupLong      float64                `protobuf:"fixed64,5,opt,name=pickup_long,json=pickupLong,proto3" json:"pickup_long,omitempty"`
	DropoffLat      float64                `protobuf:"fixed64,6,opt,name=dropoff_lat,json=dropoffLat,proto3" json:"dropoff_lat,omitempty"`
	DropoffLong     float64                `protobuf:"fixed64,7,opt,name=dropoff_long,json=dropoffLong,proto3" json:"dropoff_long,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Fare            float64                `protobuf:"fixed64,9,opt,name=fare,proto3" json:"fare,omitempty"`
	SurgeMultiplier float64                `protobuf:"fixed64,10,opt,name=surge_multiplier,json=surgeMultiplier,proto3" json:"surge_multiplier,omitempty"`
	EstimatedEta    *int32                 `protobuf:"varint,11,opt,name=estimated_eta,json=estimatedEta,proto3,oneof" json:"estimated_eta,omitempty"`
	DistanceKm      *float64               `protobuf:"fixed64,12,opt,name=distance_km,json=distanceKm,proto3,oneof" json:"distance_km,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt         *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Ride) Reset() {
	*x = Ride{}
	mi := &file_ride_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ride) ProtoMessage() {}

func (x *Ride) ProtoReflect() protoreflect.Message {
	mi := &file_ride_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ride.ProtoReflect.Descriptor instead.
func (*Ride) Descriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{6}
}

func (x *Ride) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ride) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *Ride) GetDriverId() string {
	if x != nil && x.DriverId != nil {
		return *x.DriverId
	}
	return ""
}

func (x *Ride) GetPickupLat() float64 {
	if x != nil {
		return x.PickupLat
	}
	return 0
}

func (x *Ride) GetPickupLong() float64 {
	if x != nil {
		return x.PickupLong
	}
	return 0
}

func (x *Ride) GetDropoffLat() float64 {
	if x != nil {
		return x.DropoffLat
	}
	return 0
}

func (x *Ride) GetDropoffLong() float64 {
	if x != nil {
		return x.DropoffLong
	}
	return 0
}

func (x *Ride) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Ride) GetFare() float64 {
	if x != nil {
		return x.Fare
	}
	return 0
}

func (x *Ride) GetSurgeMultiplier() float64 {
	if x != nil {
		return x.SurgeMultiplier
	}
	return 0
}

func (x *Ride) GetEstimatedEta() int32 {
	if x != nil && x.EstimatedEta != nil {
		return *x.EstimatedEta
	}
	return 0
}

func (x *Ride) GetDistanceKm() float64 {
	if x != nil && x.DistanceKm != nil {
		return *x.DistanceKm
	}
	return 0
}

func (x *Ride) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Ride) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *Ride) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Ride) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ride          *Ride                  `protobuf:"bytes,1,opt,name=ride,proto3" json:"ride,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RideResponse) Reset() {
	*x = RideResponse{}
	mi := &file_ride_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideResponse) ProtoMessage() {}

func (x *RideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ride_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideResponse.ProtoReflect.Descriptor instead.
func (*RideResponse) Descriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{7}
}

func (x *RideResponse) GetRide() *Ride {
	if x != nil {
		return x.Ride
	}
	return nil
}

type RideHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rides         []*Ride                `protobuf:"bytes,1,rep,name=rides,proto3" json:"rides,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RideHistoryResponse) Reset() {
	*x = RideHistoryResponse{}
	mi := &file_ride_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideHistoryResponse) ProtoMessage() {}

func (x *RideHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ride_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideHistoryResponse.ProtoReflect.Descriptor instead.
func (*RideHistoryResponse) Descriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{8}
}

func (x *RideHistoryResponse) GetRides() []*Ride {
	if x != nil {
		return x.Rides
	}
	return nil
}

func (x *RideHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_ride_proto protoreflect.FileDescriptor

const file_ride_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ride.proto\x12\x04ride\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x01\n" +
	"\vRideRequest\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12\x1d\n" +
	"\n" +
	"pickup_lat\x18\x02 \x01(\x01R\tpickupLat\x12\x1f\n" +
	"\vpickup_long\x18\x03 \x01(\x01R\n" +
	"pickupLong\x12\x1f\n" +
	"\vdropoff_lat\x18\x04 \x01(\x01R\n" +
	"dropoffLat\x12!\n" +
	"\fdropoff_long\x18\x05 \x01(\x01R\vdropoffLong\"I\n" +
	"\x11AcceptRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"K\n" +
	"\x13CompleteRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"E\n" +
	"\x11CancelRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\")\n" +
	"\x0eGetRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\"o\n" +
	"\x12RideHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\x96\x05\n" +
	"\x04Ride\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\x12 \n" +
	"\tdriver_id\x18\x03 \x01(\tH\x00R\bdriverId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"pickup_lat\x18\x04 \x01(\x01R\tpickupLat\x12\x1f\n" +
	"\vpickup_long\x18\x05 \x01(\x01R\n" +
	"pickupLong\x12\x1f\n" +
	"\vdropoff_lat\x18\x06 \x01(\x01R\n" +
	"dropoffLat\x12!\n" +
	"\fdropoff_long\x18\a \x01(\x01R\vdropoffLong\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x12\n" +
	"\x04fare\x18\t \x01(\x01R\x04fare\x12)\n" +
	"\x10surge_multiplier\x18\n" +
	" \x01(\x01R\x0fsurgeMultiplier\x12(\n" +
	"\restimated_eta\x18\v \x01(\x05H\x01R\festimatedEta\x88\x01\x01\x12$\n" +
	"\vdistance_km\x18\f \x01(\x01H\x02R\n" +
	"distanceKm\x88\x01\x01\x129\n" +
	"\n" +
	"started_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\f\n" +
	"\n" +
	"_driver_idB\x10\n" +
	"\x0e_estimated_etaB\x0e\n" +
	"\f_distance_km\".\n" +
	"\fRideResponse\x12\x1e\n" +
	"\x04ride\x18\x01 \x01(\v2\n" +
	".ride.RideR\x04ride\"M\n" +
	"\x13RideHistoryResponse\x12 \n" +
	"\x05rides\x18\x01 \x03(\v2\n" +
	".ride.RideR\x05rides\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xfd\x02\n" +
	"\vRideService\x126\n" +
	"\vRequestRide\x12\x11.ride.RideRequest\x1a\x12.ride.RideResponse\"\x00\x12;\n" +
	"\n" +
	"AcceptRide\x12\x17.ride.AcceptRideRequest\x1a\x12.ride.RideResponse\"\x00\x12?\n" +
	"\fCompleteRide\x12\x19.ride.CompleteRideRequest\x1a\x12.ride.RideResponse\"\x00\x12;\n" +
	"\n" +
	"CancelRide\x12\x17.ride.CancelRideRequest\x1a\x12.ride.RideResponse\"\x00\x125\n" +
	"\aGetRide\x12\x14.ride.GetRideRequest\x1a\x12.ride.RideResponse\"\x00\x12D\n" +
	"\vRideHistory\x12\x18.ride.RideHistoryRequest\x1a\x19.ride.RideHistoryResponse\"\x00B1Z/github.com/hugovillarreal/ridesharing/pkg/pb;pbb\x06proto3"

var (
	file_ride_proto_rawDescOnce sync.Once
	file_ride_proto_rawDescData []byte
)

func file_ride_proto_rawDescGZIP() []byte {
	file_ride_proto_rawDescOnce.Do(func() {
		file_ride_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ride_proto_rawDesc), len(file_ride_proto_rawDesc)))
	})
	return file_ride_proto_rawDescData
}

var file_ride_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ride_proto_goTypes = []any{
	(*RideRequest)(nil),           // 0: ride.RideRequest
	(*AcceptRideRequest)(nil),     // 1: ride.AcceptRideRequest
	(*CompleteRideRequest)(nil),   // 2: ride.CompleteRideRequest
	(*CancelRideRequest)(nil),     // 3: ride.CancelRideRequest
	(*GetRideRequest)(nil),        // 4: ride.GetRideRequest
	(*RideHistoryRequest)(nil),    // 5: ride.RideHistoryRequest
	(*Ride)(nil),                  // 6: ride.Ride
	(*RideResponse)(nil),          // 7: ride.RideResponse
	(*RideHistoryResponse)(nil),   // 8: ride.RideHistoryResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_ride_proto_depIdxs = []int32{
	9,  // 0: ride.Ride.started_at:type_name -> google.protobuf.Timestamp
	9,  // 1: ride.Ride.ended_at:type_name -> google.protobuf.Timestamp
	9,  // 2: ride.Ride.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: ride.Ride.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 4: ride.RideResponse.ride:type_name -> ride.Ride
	6,  // 5: ride.RideHistoryResponse.rides:type_name -> ride.Ride
	0,  // 6: ride.RideService.RequestRide:input_type -> ride.RideRequest
	1,  // 7: ride.RideService.AcceptRide:input_type -> ride.AcceptRideRequest
	2,  // 8: ride.RideService.CompleteRide:input_type -> ride.CompleteRideRequest
	3,  // 9: ride.RideService.CancelRide:input_type -> ride.CancelRideRequest
	4,  // 10: ride.RideService.GetRide:input_type -> ride.GetRideRequest
	5,  // 11: ride.RideService.RideHistory:input_type -> ride.RideHistoryRequest
	7,  // 12: ride.RideService.RequestRide:output_type -> ride.RideResponse
	7,  // 13: ride.RideService.AcceptRide:output_type -> ride.RideResponse
	7,  // 14: ride.RideService.CompleteRide:output_type -> ride.RideResponse
	7,  // 15: ride.RideService.CancelRide:output_type -> ride.RideResponse
	7,  // 16: ride.RideService.GetRide:output_type -> ride.RideResponse
	8,  // 17: ride.RideService.RideHistory:output_type -> ride.RideHistoryResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_ride_proto_init() }
func file_ride_proto_init() {
	if File_ride_proto != nil {
		return
	}
	file_ride_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ride_proto_rawDesc), len(file_ride_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ride_proto_goTypes,
		DependencyIndexes: file_ride_proto_depIdxs,
		MessageInfos:      file_ride_proto_msgTypes,
	}.Build()
	File_ride_proto = out.File
	file_ride_proto_goTypes = nil
	file_ride_proto_depIdxs = nil
}
