apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namePrefix: staging-

patches:
  - patch: |-
      # Staging scale
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: gateway
        namespace: rideshare
      spec:
        minReplicas: 2
        maxReplicas: 5
  - patch: |-
      # Update ingress host for staging
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: kongs-gateway-ingress
        namespace: rideshare
      spec:
        rules:
          - host: api.staging.rideshare.example.com
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: gateway
                      port:
                        number: 8080
